#ifndef __AUTOMATED_FIRMWARE_VERIFICATION_USING_FIRMWARE_HARDWARE_INTERACTION_PATTERNS_HW_H
#define __AUTOMATED_FIRMWARE_VERIFICATION_USING_FIRMWARE_HARDWARE_INTERACTION_PATTERNS_HW_H

#include <stdint.h>

uint32_t GetRegister(volatile uint32_t *);
void SetRegister(volatile uint32_t *, uint32_t);

uint32_t GetSysTick(void);

#endif /* __AUTOMATED_FIRMWARE_VERIFICATION_USING_FIRMWARE_HARDWARE_INTERACTION_PATTERNS_HW_H */